# Generated by Django 4.2 on 2025-05-07 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_emailverificationcode_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_avatar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
