# Generated by Django 4.2 on 2025-05-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_default_avatar_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_club_account',
            field=models.BooleanField(default=False, verbose_name='是否为社团账号'),
        ),
    ]
