# Generated by Django 5.2.1 on 2025-05-19 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_is_club_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_banned",
            field=models.BooleanField(default=False, verbose_name="是否被封禁"),
        ),
    ]
