# Generated by Django 5.2.1 on 2025-05-17 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("activities", "0002_activity_is_club_account"),
        ("forum", "0005_alter_post_options_remove_post_is_sticky_and_more"),
        ("materials", "0002_paymentorder"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampusNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("forum", "论坛帖子"),
                            ("material", "课件下载"),
                            ("activity", "社团活动"),
                        ],
                        max_length=20,
                        verbose_name="内容类型",
                    ),
                ),
                ("score", models.IntegerField(default=0, verbose_name="热度分数")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="activities.activity",
                        verbose_name="活动",
                    ),
                ),
                (
                    "forum_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="forum.post",
                        verbose_name="论坛帖子",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="materials.material",
                        verbose_name="课件",
                    ),
                ),
            ],
            options={
                "verbose_name": "校园火榜",
                "verbose_name_plural": "校园火榜",
                "ordering": ["-score", "-updated_at"],
            },
        ),
    ]
