# Generated by Django 4.2 on 2025-05-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostitem',
            name='item_type',
            field=models.CharField(choices=[('lost', '失物'), ('found', '招领')], default='lost', max_length=10),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lostfound_images/'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
