# Generated by Django 4.2 on 2025-05-08 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Confession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_whom', models.CharField(max_length=50, verbose_name='表白对象')),
                ('content', models.TextField(verbose_name='表白内容')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='是否匿名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('dislikes', models.PositiveIntegerField(default=0, verbose_name='点踩数')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='表白人')),
            ],
            options={
                'ordering': ['-likes', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConfessionVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField()),
                ('confession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confess.confession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'confession')},
            },
        ),
    ]
