# Generated by Django 4.2 on 2025-05-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confession',
            name='author_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='表白人名字'),
        ),
    ]
