# Generated by Django 5.2.1 on 2025-05-17 06:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("confess", "0002_confession_author_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="confession",
            options={
                "ordering": ["-likes", "-created_at"],
                "verbose_name": "表白",
                "verbose_name_plural": "表白",
            },
        ),
        migrations.AlterModelOptions(
            name="confessionvote",
            options={"verbose_name": "表白投票", "verbose_name_plural": "表白投票"},
        ),
        migrations.AddField(
            model_name="confessionvote",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="投票时间",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="confessionvote",
            name="confession",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="confess.confession",
                verbose_name="表白",
            ),
        ),
        migrations.AlterField(
            model_name="confessionvote",
            name="is_like",
            field=models.BooleanField(verbose_name="是否点赞"),
        ),
        migrations.AlterField(
            model_name="confessionvote",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
    ]
