# Generated by Django 4.2 on 2025-05-09 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_club_account',
            field=models.BooleanField(default=False, verbose_name='是否为社团账号'),
        ),
    ]
