# Generated by Django 4.2 on 2025-05-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_post_tags_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='图片链接'),
        ),
    ]
