# Generated by Django 5.2.1 on 2025-05-19 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0005_alter_post_options_remove_post_is_sticky_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SensitiveWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "word",
                    models.CharField(max_length=50, unique=True, verbose_name="敏感词"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "敏感词",
                "verbose_name_plural": "敏感词列表",
            },
        ),
        migrations.CreateModel(
            name="UserViolationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_content", models.TextField(verbose_name="原始内容")),
                ("filtered_content", models.TextField(verbose_name="过滤后内容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "violation_type",
                    models.CharField(
                        choices=[("post", "帖子"), ("comment", "评论")],
                        default="post",
                        max_length=20,
                        verbose_name="违规类型",
                    ),
                ),
                (
                    "sensitive_word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="forum.sensitiveword",
                        verbose_name="敏感词",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="violation_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户违规记录",
                "verbose_name_plural": "用户违规记录",
            },
        ),
    ]
